---
title: "Replication 1"
author: "Hannah Hardenbergh and Helen Simpson"
date: "2/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load necessary libraries.

library(devtools)
library(gt)
library(tidyverse)
library(stargazer)
library(knitr)
library(kableExtra)

# Load data. rename dataframes for ease of mind.

data_case <- read_csv("glynn_sen_daughters_by_case_1.csv")
data_judge <- read_csv("glynn_sen_daughters_by_judge.csv")

read_csv("glynn_sen_daughters_replication_code.R")


```

```{r Table 1}
# subset the judges data frame to exclude judges without daughters

judges <- subset(data_judge, girls != "NaN")

# create a table for how many children democratic and republican judges have 

row1 <- table(judges$republican, judges$child)

# create a table for how many daughters democratic and republican judges have

row2 <- table(judges$republican, judges$girls)

# print tables

row1

row2

# add row names and styling

kable(row1, 
      caption = "Number of Children and Girls for U.S. Courts of Appeals Judges Participating in Gender-Related Cases, 1996-2002")

```


```{r Table 2}
table_2 <- data_judge %>% 
  select(republican,
         girls,
         child) %>% 
  summarise(mean_girls = mean(girls),
            mean_child = mean(child)) %>%
  mutate(no_child = ifelse)
  
table_2 %>% 
  lm()

```

```{r}

```



